version: 2.1

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - attach_workspace:
          at: ~/ci-meets-cd
      - run:
          name: create cloudformation stack
          command: |
            aws cloudformation create-stack --stack-name ci-meets-cd \ 
              --template-body file://~/ci-meets-cd/aws/template.yml  \
              --parameters file://~/ci-meets-cd/aws/template-parameters.json \
              --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM" \
              --region=us-east-1
    
workflow:
  build:
    jobs:
      - create_infrastructure