AWSTemplateFormatVersion: "2010-09-09"
Description: "Remake of old template for creating an EC2 instance."
Parameters:
  EnvironmentName:
    Description: "A name to the Environment where everything will be fixed to."
    Type: String
  VpcId:
    Description: "VPC identification."
    Type: String
  AmiId:
    Description: "AMI identification to be used."
    Type: String
  InstanceType:
    Description: "Type for the instance"
    Default: "t2.micro"
    Type: String
  SubnetId:
    Description: "Subnet to be used."
    Type: String
Resources:
  SecurityGroupServer:
    Type: AWS::EC2::SecurityGroup
    Description: "Security Group for the EC2 instance that receives the IaC jobs from CircleCI"
    GroupName: !Sub ${EnvironmentName}WebServerSecGroup
    SecurityGroupEgress: 
      - IpProtocol: tcp
        FromPort: 0
        ToPort: 65535
        CidrIp: 0.0.0.0/0
    SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
    Tags:
      - Value: Project
        Key: !Ref EnvironmentName
    VpcId: !Ref VpcId

    DevelopmentServer:
      Type: AWS::EC2::Instance
      Description: "This is the instance that will be used as infrastructure."
      ImageId: !Ref AmiId
      KeyName: AWS_EC2_Demo_keypair
      InstanceType: !Ref InstanceType
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: !Ref SubnetId
          GroupSet: 
            - !Ref SecurityGroupServer
      Tags:
        - Value: Project
          Key: !Ref EnvironmentName
